name: CI stage

# Triggers
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev_python_apis
    
    # üîê Required to publish SARIF to GitHub Security
    permissions:
      contents: read
      security-events: write
    steps:
    # Downloads the code (clone the code)
      -
        name: Checkout
        uses: actions/checkout@v5
    #  Guarantee a consistent Python runtime on the CI runner when executing tests outside Docker.
      - 
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      # STO - SAST - SEMGREP
      - 
        name: Install Semgrep
        run: |
          pip install semgrep
      
      - 
        name: Run Semgrep vulnerability scanner
        run: |
          semgrep scan \
            --config p/ci,p/python \
            --sarif \
            --output semgrep-results.sarif
      - 
        name: Upload Semgrep scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'semgrep-results.sarif'

      # Install dependencies
      - 
        name: Install dependencies
        run: |
          pip install -r requirements.txt
      # Run tests
      - 
        name: Run tests
        run: |
          pytest -v

#Docker steps
    # Login to Docker
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_NAME }}
          password: ${{ secrets.SECRET_DOCKER }}
      #Build and push to dockerhub
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKER_NAME }}/apis_python:latest
            ${{ vars.DOCKER_NAME }}/apis_python:${{ github.sha }}
