name: CI stage

# Triggers
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - k8s/**
      - images/**

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev_python_apis
    
    steps:
    # Downloads the code (clone the code)
      -
        name: Checkout
        uses: actions/checkout@v5
    #  Guarantee a consistent Python runtime on the CI runner when executing tests outside Docker.
      - 
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      # Install dependencies
      - 
        name: Install dependencies
        run: |
          pip install -r requirements.txt
      # Run tests
      - 
        name: Run tests
        run: |
          pytest -v

#Docker steps
    # Login to Docker
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_NAME }}
          password: ${{ secrets.SECRET_DOCKER }}
      #Build and push to dockerhub
      #Build a local image to test with the scanner
      - 
        name: Build Docker image (local)
        run: |
          docker build -t ${{ vars.DOCKER_NAME }}/apis_python:ci .
      #Creating STO best practices, container Scannin
      - 
        name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ vars.DOCKER_NAME }}/apis_python:ci
          format: table
          severity: CRITICAL
          exit-code: 1
      #Push into Dockerhub with the latest and the sha tags.
      - 
        name: Push Docker image
        run: |
          docker tag ${{ vars.DOCKER_NAME }}/apis_python:ci ${{ vars.DOCKER_NAME }}/apis_python:latest
          docker tag ${{ vars.DOCKER_NAME }}/apis_python:ci ${{ vars.DOCKER_NAME }}/apis_python:${{ github.sha }}
          docker push ${{ vars.DOCKER_NAME }}/apis_python:latest
          docker push ${{ vars.DOCKER_NAME }}/apis_python:${{ github.sha }}
